ASSESSMENT_SETTINGS = {
"get_systempackage_by_systemkey_compliance_json.py",
"get_systempackage_by_systemkey_compliance_by_complianceid_allcontrolscore_json.py",
"get_systempackage_by_systemkey_poam_json.py",
"get_systempackage_by_systemkey_patchscore_json.py",
"get_systempackage_by_systemkey_approvedpps_json.py",
"get_systempackage_by_systemkey_checklists_json.py",
"get_systempackage_by_systemkey_techvulnerabilitydata_json.py",
"get_systempackage_by_systemkey_missingdata_json.py",
"get_systempackage_by_systemkey_hardware_json.py"
}